"""Mock places data with real German cities and coordinates"""

MOCK_PLACES = [
    # Berlin
    {
        "name": "Café Einstein Stammhaus",
        "description": "Historic Viennese-style café in a beautiful villa. Perfect for meetings and casual work.",
        "address": "Kurfürstenstraße 58",
        "city": "Berlin",
        "postal_code": "10785",
        "latitude": 52.5065,
        "longitude": 13.3657,
        "category": "cafe",
        "image_url": "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800",
    },
    {
        "name": "Betahaus Coworking",
        "description": "Creative coworking space in Kreuzberg. Great community and events.",
        "address": "Rudi-Dutschke-Straße 23",
        "city": "Berlin",
        "postal_code": "10969",
        "latitude": 52.5071,
        "longitude": 13.3915,
        "category": "coworking",
        "image_url": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
    },
    {
        "name": "Tiergarten Park",
        "description": "Berlin's most popular inner-city park. Great for outdoor meetings and relaxation.",
        "address": "Straße des 17. Juni",
        "city": "Berlin",
        "postal_code": "10785",
        "latitude": 52.5145,
        "longitude": 13.3501,
        "category": "park",
        "image_url": "https://images.unsplash.com/photo-1585208798174-6cedd86e019a?w=800",
    },
    
    # Munich
    {
        "name": "Münchner Freiheit Café",
        "description": "Cozy café in Schwabing with great coffee and atmosphere.",
        "address": "Münchner Freiheit 20",
        "city": "Munich",
        "postal_code": "80802",
        "latitude": 48.1631,
        "longitude": 11.5880,
        "category": "cafe",
        "image_url": "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800",
    },
    {
        "name": "WERK1 Coworking",
        "description": "Modern coworking space near Ostbahnhof with excellent facilities.",
        "address": "Grafinger Straße 6",
        "city": "Munich",
        "postal_code": "81671",
        "latitude": 48.1279,
        "longitude": 11.6042,
        "category": "coworking",
        "image_url": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800",
    },
    {
        "name": "Englischer Garten",
        "description": "One of the world's largest urban parks. Perfect for outdoor activities.",
        "address": "Englischer Garten",
        "city": "Munich",
        "postal_code": "80538",
        "latitude": 48.1642,
        "longitude": 11.6056,
        "category": "park",
        "image_url": "https://images.unsplash.com/photo-1580541631950-7282082b53ce?w=800",
    },
    
    # Hamburg
    {
        "name": "Elbgold Café",
        "description": "Specialty coffee roastery and café in the heart of Hamburg.",
        "address": "Lagerstraße 34c",
        "city": "Hamburg",
        "postal_code": "20357",
        "latitude": 53.5625,
        "longitude": 9.9654,
        "category": "cafe",
        "image_url": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
    },
    {
        "name": "Spaces Altona",
        "description": "Professional coworking space with harbor views.",
        "address": "Große Elbstraße 277",
        "city": "Hamburg",
        "postal_code": "22767",
        "latitude": 53.5413,
        "longitude": 9.9269,
        "category": "coworking",
        "image_url": "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800",
    },
    {
        "name": "Planten un Blomen",
        "description": "Beautiful park in the center of Hamburg with Japanese garden.",
        "address": "Marseiller Straße",
        "city": "Hamburg",
        "postal_code": "20355",
        "latitude": 53.5633,
        "longitude": 9.9822,
        "category": "park",
        "image_url": "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800",
    },
    
    # Frankfurt
    {
        "name": "Café Wacker",
        "description": "Traditional Frankfurt café with excellent pastries.",
        "address": "Kornmarkt 9",
        "city": "Frankfurt",
        "postal_code": "60311",
        "latitude": 50.1109,
        "longitude": 8.6821,
        "category": "cafe",
        "image_url": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
    },
    {
        "name": "Die Zentrale Coworking",
        "description": "Collaborative workspace in Frankfurt's city center.",
        "address": "Berger Straße 175",
        "city": "Frankfurt",
        "postal_code": "60385",
        "latitude": 50.1241,
        "longitude": 8.7040,
        "category": "coworking",
        "image_url": "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800",
    },
    {
        "name": "Palmengarten",
        "description": "Botanical garden perfect for peaceful meetings.",
        "address": "Siesmayerstraße 61",
        "city": "Frankfurt",
        "postal_code": "60323",
        "latitude": 50.1236,
        "longitude": 8.6594,
        "category": "park",
        "image_url": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
    },
    
    # Cologne
    {
        "name": "Café Reichard",
        "description": "Historic café with view of Cologne Cathedral.",
        "address": "Unter Fettenhennen 11",
        "city": "Cologne",
        "postal_code": "50667",
        "latitude": 50.9413,
        "longitude": 6.9583,
        "category": "cafe",
        "image_url": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
    },
    {
        "name": "Coboat Coworking",
        "description": "Unique coworking space on a boat!",
        "address": "Agrippinawerft 28",
        "city": "Cologne",
        "postal_code": "50678",
        "latitude": 50.9282,
        "longitude": 6.9649,
        "category": "coworking",
        "image_url": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
    },
    {
        "name": "Rheinpark",
        "description": "Park along the Rhine with beautiful city views.",
        "address": "Auenweg 35",
        "city": "Cologne",
        "postal_code": "50679",
        "latitude": 50.9461,
        "longitude": 6.9825,
        "category": "park",
        "image_url": "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800",
    },
    
    # Stuttgart
    {
        "name": "Café Künstlerbund",
        "description": "Artistic café in the heart of Stuttgart.",
        "address": "Schlossplatz 2",
        "city": "Stuttgart",
        "postal_code": "70173",
        "latitude": 48.7784,
        "longitude": 9.1800,
        "category": "cafe",
        "image_url": "https://images.unsplash.com/photo-1559496417-e7f25c7e90c7?w=800",
    },
    {
        "name": "Impact Hub Stuttgart",
        "description": "Community-focused coworking space for changemakers.",
        "address": "Friedrichstraße 10",
        "city": "Stuttgart",
        "postal_code": "70174",
        "latitude": 48.7758,
        "longitude": 9.1829,
        "category": "coworking",
        "image_url": "https://images.unsplash.com/photo-1497366672149-e5e4b4d34eb3?w=800",
    },
    {
        "name": "Schlossgarten",
        "description": "Large park in the city center, perfect for outdoor meetings.",
        "address": "Schloßstraße",
        "city": "Stuttgart",
        "postal_code": "70173",
        "latitude": 48.7847,
        "longitude": 9.1829,
        "category": "park",
        "image_url": "https://images.unsplash.com/photo-1571988640154-ae9bcd1e1b08?w=800",
    },
    
    # Düsseldorf
    {
        "name": "Café Hüftgold",
        "description": "Trendy café in Flingern neighborhood.",
        "address": "Ackerstraße 141",
        "city": "Düsseldorf",
        "postal_code": "40233",
        "latitude": 51.2308,
        "longitude": 6.7989,
        "category": "cafe",
        "image_url": "https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800",
    },
    {
        "name": "Startplatz Coworking",
        "description": "Tech-focused coworking space with events.",
        "address": "Speditionstraße 15A",
        "city": "Düsseldorf",
        "postal_code": "40221",
        "latitude": 51.2172,
        "longitude": 6.7875,
        "category": "coworking",
        "image_url": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800",
    },
    {
        "name": "Hofgarten",
        "description": "Historic park in the city center.",
        "address": "Hofgarten",
        "city": "Düsseldorf",
        "postal_code": "40213",
        "latitude": 51.2334,
        "longitude": 6.7772,
        "category": "park",
        "image_url": "https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=800",
    },
]
